import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import SideNavigation from "@/components/common/navigation/SideNavigation";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Shadcn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} antialiased`}>
        <SideNavigation />
        {children}
      </body>
    </html>
  );
}
